#!/bin/bash

# ============================================================
# Devosia curated genome download/reconciliation
#
# Purpose:
#   Reconcile genomes/proteins/GFF files with the curated
#   accession list generated by Pipeline1_Data_curation.R.
#
#   - Removes files for accessions no longer in the curated list.
#   - Downloads newly added/missing accessions.
#   - Does NOT re-download accessions already present.
#
# Input:
#   data/metadata/devosia_accessions.txt
#
# Outputs:
#   genomes/
#   proteins/
#   gff/
#   devosia_raw_merge/
#   chunks/
#   batch_zips/
#
# Portability:
#   The repository root is inferred from the location of this
#   script. The workflow therefore does not depend on a
#   user-specific filesystem path or current working directory.
# ============================================================

set -e

## ---- Determine repository root ----

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

cd "$PROJECT_ROOT"

## ---- Input ----

ACCESSION_FILE="data/metadata/devosia_accessions.txt"

if [ ! -f "$ACCESSION_FILE" ]; then
    echo "ERROR: Curated accession file not found:"
    echo "  $PROJECT_ROOT/$ACCESSION_FILE"
    echo
    echo "Run Pipeline1_Data_curation.R first."
    exit 1
fi

CHUNK_SIZE=8
MAX_RETRIES=5

n_acc=$(wc -l < "$ACCESSION_FILE")

echo "=== Devosia curated genome download/reconciliation ==="
echo "Project root: $PROJECT_ROOT"
echo "Accession file: $ACCESSION_FILE"
echo "Current curated accession count: $n_acc"

## ---- Create required directories ----

mkdir -p \
    chunks \
    batch_zips \
    devosia_raw_merge \
    genomes \
    proteins \
    gff

## ---- 1. Find accessions currently on disk ----

ls genomes 2>/dev/null |
    sed -E 's/(_genomic)?\.fna$//' |
    sed -E 's/^(GC[AF]_[0-9]+\.[0-9]+).*/\1/' |
    sort -u > have_genomes.txt

sort "$ACCESSION_FILE" > want.txt

## ---- 2. Remove stale accessions ----

to_remove=$(comm -23 have_genomes.txt want.txt)

if [ -n "$to_remove" ]; then

    echo ""
    echo "=== Removing files for accessions dropped from curated list ==="

    for acc in $to_remove; do

        echo "Removing $acc"

        rm -fv genomes/${acc}*
        rm -fv proteins/${acc}*
        rm -fv gff/${acc}*

    done

else

    echo "No stale accessions to remove."

fi

## ---- 3. Find missing accessions ----

to_download=$(comm -13 have_genomes.txt want.txt)

if [ -z "$to_download" ]; then

    echo ""
    echo "All $n_acc curated accessions already present -- nothing to download."

else

    echo ""
    echo "=== Downloading $(echo "$to_download" | wc -l) new/missing accession(s) ==="

    echo "$to_download" > chunks/to_download.txt

    split \
        -l "$CHUNK_SIZE" \
        chunks/to_download.txt \
        chunks/chunk_ \
        --additional-suffix=.txt

    rm -f chunks/to_download.txt

    failed_chunks=""

    for chunk in chunks/chunk_*.txt; do

        chunk_name=$(basename "$chunk" .txt)
        out_zip="batch_zips/${chunk_name}.zip"

        attempt=1
        success=0

        while [ $attempt -le $MAX_RETRIES ]; do

            echo "--- Downloading $chunk_name (attempt $attempt/$MAX_RETRIES) ---"

            datasets download genome accession \
                --inputfile "$chunk" \
                --include genome,protein,gff3 \
                --filename "$out_zip" || true

            if [ -f "$out_zip" ] &&
               unzip -t "$out_zip" > /dev/null 2>&1; then

                echo "$chunk_name OK"
                success=1
                break

            else

                echo "$chunk_name failed or corrupt, retrying..."

                rm -f "$out_zip"

                attempt=$((attempt + 1))

                sleep 5

            fi

        done

        [ $success -eq 0 ] &&
            failed_chunks="$failed_chunks $chunk_name"

    done

    if [ -n "$failed_chunks" ]; then

        echo ""
        echo "WARNING: Chunks that never succeeded:"
        echo "$failed_chunks"

    fi

    echo ""
    echo "=== Extracting and merging new downloads ==="

    for z in batch_zips/chunk_*.zip; do

        [ -f "$z" ] || continue

        rm -rf tmp_extract

        unzip -o "$z" -d tmp_extract > /dev/null

        cp -r \
            tmp_extract/ncbi_dataset/data/* \
            devosia_raw_merge/ \
            2>/dev/null || true

        rm -rf tmp_extract

    done

    ## ---- Copy per-accession files ----

    for d in devosia_raw_merge/*/; do

        [ -d "$d" ] || continue

        acc=$(basename "$d")

        fna=$(ls "$d"*_genomic.fna 2>/dev/null | head -1)

        [ -n "$fna" ] &&
            cp "$fna" "genomes/"

        [ -f "${d}protein.faa" ] &&
            cp "${d}protein.faa" "proteins/${acc}.faa"

        [ -f "${d}genomic.gff" ] &&
            cp "${d}genomic.gff" "gff/${acc}.gff"

    done

fi

## ---- 4. Final completeness check ----

echo ""
echo "=== Final completeness check ==="

n_genomes=$(ls genomes | wc -l)
n_proteins=$(ls proteins | wc -l)
n_gff=$(ls gff | wc -l)

echo "Expected accessions: $n_acc"
echo "Genomes:            $n_genomes"
echo "Proteins:           $n_proteins"
echo "GFF:                $n_gff"

ls genomes |
    sed -E 's/(_genomic)?\.fna$//' |
    sed -E 's/^(GC[AF]_[0-9]+\.[0-9]+).*/\1/' |
    sort -u > have_genomes.txt

still_missing=$(comm -23 want.txt have_genomes.txt)

if [ -z "$still_missing" ]; then

    echo "All $n_acc curated genome accessions present."

else

    echo "Still missing:"
    echo "$still_missing"

fi

## ---- Protein completeness ----

if [ "$n_proteins" -lt "$n_acc" ]; then

    n_gap=$((n_acc - n_proteins))

    echo ""
    echo "NOTE: $n_gap accession(s) have no protein.faa."
    echo "This can occur for GenBank-only, non-PGAP assemblies."
    echo "Cross-check against:"
    echo "  data/metadata/devosia_curated_keep_only.tsv"

    comm -23 \
        want.txt \
        <(ls proteins | sed 's/\.faa$//' | sort)

fi

## ---- GFF completeness ----

if [ "$n_gff" -lt "$n_acc" ]; then

    echo "NOTE: $((n_acc - n_gff)) accession(s) have no genomic.gff."

fi

## ---- Final status ----

if [ -z "$still_missing" ] &&
   [ "$n_genomes" -eq "$n_acc" ]; then

    echo ""
    echo "Ready for Phase 4 (CheckM2)."

fi
